using System.Net;
using System.Text;
using SpaceTree.Core.Model;
using SpaceTree.Core.Util;

namespace SpaceTree.Core.Export;

/// <summary>
/// Writes a self-contained HTML report with inline CSS and proportional bars.
/// Self-contained matters: the file can be mailed to someone, and "Print to PDF"
/// from any browser produces a clean paginated document with no extra tooling.
/// </summary>
public static class HtmlReportExporter
{
    public static void Write(TextWriter writer, IEnumerable<ExportRow> rows, ReportMetadata metadata,
        SizeUnitSystem units = SizeUnitSystem.Binary)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(rows);
        ArgumentNullException.ThrowIfNull(metadata);

        writer.Write(HeadHtml);
        writer.Write("<h1>Disk Space Report</h1>");
        writer.Write("<p class=\"root\">");
        writer.Write(Encode(metadata.RootPath));
        writer.Write("</p>");

        writer.Write("<div class=\"meta\">");
        WriteMetaItem(writer, "Total size", SizeFormatter.Format(metadata.TotalSize, units));
        WriteMetaItem(writer, "Allocated", SizeFormatter.Format(metadata.TotalAllocated, units));
        WriteMetaItem(writer, "Files", SizeFormatter.FormatCount(metadata.FileCount));
        WriteMetaItem(writer, "Folders", SizeFormatter.FormatCount(metadata.FolderCount));
        if (metadata.Volume is { TotalBytes: > 0 } volume)
        {
            WriteMetaItem(writer, "Volume free", SizeFormatter.Format(volume.FreeBytes, units));
            WriteMetaItem(writer, "Volume capacity", SizeFormatter.Format(volume.TotalBytes, units));
        }
        WriteMetaItem(writer, "Scanned", metadata.CompletedAt.ToString("f"));
        if (metadata.Duration > TimeSpan.Zero)
            WriteMetaItem(writer, "Scan time", SizeFormatter.FormatDuration(metadata.Duration));
        writer.Write("</div>");

        writer.Write("<table><thead><tr>");
        writer.Write("<th class=\"name\">Name</th><th class=\"num\">Size</th><th class=\"num\">Allocated</th>");
        writer.Write("<th class=\"bar\">% of Parent</th><th class=\"num\">Files</th><th class=\"num\">Folders</th>");
        writer.Write("<th class=\"date\">Last Modified</th>");
        writer.Write("</tr></thead><tbody>");

        foreach (var row in rows)
        {
            double pct = Math.Clamp(row.PercentOfParent, 0, 1);

            writer.Write("<tr class=\"");
            writer.Write(row.IsFile ? "file" : "folder");
            writer.Write("\"><td class=\"name\"><span class=\"ind\" style=\"width:");
            writer.Write((Math.Min(row.Depth, 24) * 16).ToString());
            writer.Write("px\"></span><span class=\"ico\">");
            writer.Write(row.IsFile ? "&#128196;" : "&#128193;");
            writer.Write("</span>");
            writer.Write(Encode(row.Name));
            writer.Write("</td>");

            WriteNumeric(writer, SizeFormatter.Format(row.Size, units));
            WriteNumeric(writer, SizeFormatter.Format(row.Allocated, units));

            writer.Write("<td class=\"bar\"><div class=\"track\"><div class=\"fill\" style=\"width:");
            writer.Write((pct * 100).ToString("F1", System.Globalization.CultureInfo.InvariantCulture));
            writer.Write("%\"></div></div><span class=\"pct\">");
            writer.Write(SizeFormatter.FormatPercent(pct));
            writer.Write("</span></td>");

            WriteNumeric(writer, row.IsFile ? string.Empty : SizeFormatter.FormatCount(row.FileCount));
            WriteNumeric(writer, row.IsFile ? string.Empty : SizeFormatter.FormatCount(row.FolderCount));

            writer.Write("<td class=\"date\">");
            writer.Write(Encode(SizeFormatter.FormatDate(row.LastModified)));
            writer.Write("</td></tr>");
        }

        writer.Write("</tbody></table>");

        if (metadata.Errors.Count > 0)
        {
            writer.Write("<h2>Inaccessible locations (");
            writer.Write(metadata.Errors.Count.ToString());
            writer.Write(")</h2><ul class=\"errors\">");
            foreach (var error in metadata.Errors.Take(200))
            {
                writer.Write("<li><code>");
                writer.Write(Encode(error.Path));
                writer.Write("</code> &mdash; ");
                writer.Write(Encode(error.Message));
                writer.Write("</li>");
            }
            if (metadata.Errors.Count > 200)
                writer.Write("<li>&hellip; and more</li>");
            writer.Write("</ul>");
        }

        writer.Write("<p class=\"footer\">Generated by SpaceTree</p></body></html>");
    }

    public static void WriteToFile(string path, IEnumerable<ExportRow> rows, ReportMetadata metadata,
        SizeUnitSystem units = SizeUnitSystem.Binary)
    {
        using var writer = new StreamWriter(path, false, new UTF8Encoding(false));
        Write(writer, rows, metadata, units);
    }

    private static void WriteNumeric(TextWriter writer, string value)
    {
        writer.Write("<td class=\"num\">");
        writer.Write(Encode(value));
        writer.Write("</td>");
    }

    private static void WriteMetaItem(TextWriter writer, string label, string value)
    {
        writer.Write("<div class=\"item\"><span class=\"label\">");
        writer.Write(Encode(label));
        writer.Write("</span><span class=\"value\">");
        writer.Write(Encode(value));
        writer.Write("</span></div>");
    }

    private static string Encode(string? value) => WebUtility.HtmlEncode(value ?? string.Empty);

    private const string HeadHtml = """
        <!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
        <title>SpaceTree Disk Space Report</title>
        <style>
        :root{--fg:#1a1d21;--muted:#6b7280;--line:#e5e7eb;--accent:#2563eb;--track:#f1f5f9;--bg:#fff}
        *{box-sizing:border-box}
        body{font:13px/1.45 "Segoe UI",system-ui,-apple-system,sans-serif;color:var(--fg);background:var(--bg);margin:32px;max-width:1200px}
        h1{font-size:22px;font-weight:600;margin:0 0 4px}
        h2{font-size:15px;font-weight:600;margin:28px 0 8px}
        .root{font-family:Consolas,"Cascadia Mono",monospace;color:var(--muted);margin:0 0 18px;word-break:break-all}
        .meta{display:flex;flex-wrap:wrap;gap:8px 28px;padding:14px 16px;border:1px solid var(--line);border-radius:8px;margin-bottom:22px;background:#fafbfc}
        .meta .item{display:flex;flex-direction:column;gap:2px}
        .meta .label{font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted)}
        .meta .value{font-size:14px;font-weight:600;font-variant-numeric:tabular-nums}
        table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums}
        thead th{text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:var(--muted);
          border-bottom:1px solid var(--line);padding:6px 10px;font-weight:600}
        th.num,td.num{text-align:right;white-space:nowrap}
        td{padding:4px 10px;border-bottom:1px solid #f4f5f7;vertical-align:middle}
        td.name{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:520px}
        .ind{display:inline-block}
        .ico{margin-right:6px;opacity:.75}
        tr.file td.name{color:var(--muted)}
        td.bar{width:190px}
        .track{display:inline-block;width:110px;height:9px;background:var(--track);border-radius:5px;overflow:hidden;vertical-align:middle}
        .fill{height:100%;background:var(--accent);border-radius:5px}
        .pct{display:inline-block;width:64px;text-align:right;color:var(--muted);font-size:12px}
        td.date{color:var(--muted);white-space:nowrap}
        .errors{color:var(--muted);font-size:12px;padding-left:18px}
        .errors code{color:var(--fg)}
        .footer{margin-top:28px;color:var(--muted);font-size:11px}
        @media print{
          body{margin:0;font-size:10px;max-width:none}
          thead{display:table-header-group}
          tr{page-break-inside:avoid}
          .meta{background:none}
          .fill{-webkit-print-color-adjust:exact;print-color-adjust:exact}
        }
        </style></head><body>
        """;
}

/// <summary>Header information shown at the top of a report.</summary>
public sealed class ReportMetadata
{
    public required string RootPath { get; init; }
    public long TotalSize { get; init; }
    public long TotalAllocated { get; init; }
    public long FileCount { get; init; }
    public long FolderCount { get; init; }
    public TimeSpan Duration { get; init; }
    public DateTime CompletedAt { get; init; } = DateTime.Now;
    public VolumeInfo? Volume { get; init; }
    public IReadOnlyList<ScanError> Errors { get; init; } = Array.Empty<ScanError>();

    public static ReportMetadata FromScan(ScanResult result) => new()
    {
        RootPath = result.RootPath,
        TotalSize = result.TotalSize,
        TotalAllocated = result.TotalAllocated,
        FileCount = result.FileCount,
        FolderCount = result.DirectoryCount,
        Duration = result.Duration,
        CompletedAt = result.CompletedAt,
        Volume = result.Volume,
        Errors = result.Errors,
    };
}
